version: '3.8'

services:
  real_estate_agent:
    build: .
    image: real-estate-agent:latest
    container_name: real-estate-agent
    volumes:
      - ./logs:/project/logs
      - ./data:/project/data
      - ./.env:/project/.env
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}